version: '2.1'
services:
  lpaas-ws:
    build: ../lpaas-ws/
    ports:
      - "8080:8080"
    logging:
      driver: none
  web-chill:
    build: ./web-chill/.
    ports: 
      - "5000:5000"
    links:
     - lpaas-ws
    environment:
     LPAAS_IP: "lpaas-ws"
     WAIT_LPAAS: 5000
    depends_on:
      - lpaas-ws
  second-web-chill:
    build: ./web-chill/.
    ports: 
      - "5001:5000"
    links:
     - lpaas-ws
    environment:
     LPAAS_IP: "lpaas-ws"
     WAIT_LPAAS: 5000
    depends_on:
      - lpaas-ws